'use strict';
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
let kind='url', last=null, extensionReady=false, protectionEnabled=false;
let history=[]; try {history=JSON.parse(localStorage.getItem('fatin-history')||'[]');if(!Array.isArray(history))history=[];}catch{}
let base=localStorage.getItem('fatin-server')||'', token=sessionStorage.getItem('fatin-token')||'';
const names={home:'نظرة عامة',scan:'الفحص الذكي',advisor:'مستشار فطن',history:'سجل الفحوصات',report:'إعداد بلاغ',settings:'الإعدادات'};
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
function page(id){if(!names[id])return;$$('.page').forEach(n=>n.classList.toggle('active',n.id===id));$$('nav button').forEach(n=>n.classList.toggle('active',n.dataset.page===id));$('#pageTitle').textContent=names[id];if(id==='history')renderHistory();location.hash=id;window.scrollTo(0,0);}
$$('[data-page]').forEach(n=>n.addEventListener('click',()=>page(n.dataset.page)));
window.addEventListener('hashchange',()=>page(location.hash.slice(1)||'home'));if(names[location.hash.slice(1)])page(location.hash.slice(1));
function setKind(k){kind=k;$$('[data-kind]').forEach(n=>{n.classList.toggle('active',n.dataset.kind===k);n.setAttribute('aria-selected',n.dataset.kind===k)});['url','text','file'].forEach(x=>$('#'+x+'Input').hidden=x!==k);$('#scanError').textContent='';}
$$('[data-kind]').forEach(n=>n.addEventListener('click',()=>setKind(n.dataset.kind)));
$$('[data-scan]').forEach(n=>n.addEventListener('click',()=>{setKind(n.dataset.scan);page('scan')}));
$('#fileValue').addEventListener('change',()=>$('#filename').textContent=$('#fileValue').files[0]?.name||'');
async function api(path,body){const controller=new AbortController(), timeout=setTimeout(()=>controller.abort(),45000);try{const headers={};if(token)headers.Authorization='Bearer '+token;if(!(body instanceof FormData)&&body!==undefined)headers['Content-Type']='application/json';const r=await fetch(base+'/api/'+path,{method:body===undefined?'GET':'POST',headers,body:body===undefined?undefined:body instanceof FormData?body:JSON.stringify(body),signal:controller.signal});let d;try{d=await r.json()}catch{throw Error('لم يرسل الخادم نتيجة صحيحة. تحقق من عنوانه في الإعدادات.')}if(!r.ok)throw Error(d.error||'تعذر تنفيذ الطلب');return d;}catch(e){if(e.name==='AbortError')throw Error('انتهت مهلة الاتصال؛ حاول مجددًا.');if(e instanceof TypeError)throw Error('تعذر الاتصال بالخادم. افتح الإعدادات وتحقق من الرابط.');throw e;}finally{clearTimeout(timeout)}}
async function health(){try{const d=await api('health');$('#connection').textContent=d.ai_configured?'Gemini مُعدّ على الخادم':'فحص أولي · Gemini غير مفعّل';$('#connection').classList.toggle('muted',!d.ai_configured);$('#engineName').textContent=d.ai_configured?'Gemini + قواعد':'قواعد أولية';$('#engineNote').textContent=d.ai_configured?'تم إعداد المفتاح؛ نجاح الطلب يتحقق عند الفحص':'فحص محدود دون ذكاء اصطناعي';return true;}catch(e){$('#connection').textContent='الخادم غير متصل';$('#connection').classList.add('muted');$('#engineNote').textContent='حدد عنوان الخادم في الإعدادات';return false;}}
$('#scanForm').addEventListener('submit',async e=>{e.preventDefault();$('#scanError').textContent='';const btn=$('#scanBtn');btn.disabled=true;btn.textContent='جارٍ تحليل المؤشرات…';try{if(!$('#consent').checked)throw Error('أكد موافقتك قبل الفحص.');let body,path='analyze';if(kind==='file'){const f=$('#fileValue').files[0];if(!f)throw Error('اختر ملفًا أولًا.');if(f.size>5*1024*1024)throw Error('الحد الأقصى 5 ميجابايت.');body=new FormData();body.append('file',f);body.append('ai_consent','true');path='file';}else{const value=$('#'+kind+'Value').value.trim();if(!value)throw Error('أدخل المحتوى للفحص.');body={kind,value,ai_consent:true};}const d=await api(path,body);last=d;renderResult(d);makeReport(d);}catch(e){$('#scanError').textContent=e.message;}finally{btn.disabled=false;btn.textContent='✦ ابدأ الفحص';}});
const riskNames={high:'مؤشرات اشتباه مرتفعة',medium:'مؤشرات تستدعي التحقق',unknown:'نتيجة غير حاسمة'};
function renderResult(d){const out=$('#result');out.replaceChildren();out.append(el('span',riskNames[d.risk]||'غير حاسمة','badge risk-'+d.risk),el('h2','نتيجة الفحص'),el('p',d.summary,'summary'));if(d.notice)out.append(el('p',d.notice,'notice'));out.append(el('small',d.engine==='gemini'?'تحليل Gemini مع قواعد أولية':'فحص بالقواعد الأولية'));for(const row of d.indicators||[]){const card=el('div',undefined,'indicator');card.append(el('strong',row.title),el('div',row.evidence,'evidence'),el('p',row.explanation));out.append(card)}if(!(d.indicators||[]).length)out.append(el('p','لا توجد مؤشرات ضمن الفحص المتاح؛ هذا لا يثبت السلامة.'));out.append(el('h3','الخطوة المناسبة'));const list=el('ol');for(const a of d.actions||[])list.append(el('li',a));out.append(list,el('div',d.limitation,'note'));if(d.file)out.append(el('small','SHA-256: '+d.file.sha256,'evidence'));const actions=el('div',undefined,'actions'),save=el('button','حفظ ملخص النتيجة','secondary'),report=el('button','إعداد بلاغ','primary');save.addEventListener('click',()=>{try{history.unshift({risk:d.risk,summary:d.summary,engine:d.engine,time:new Date().toISOString()});history=history.slice(0,50);localStorage.setItem('fatin-history',JSON.stringify(history));stats();save.textContent='تم الحفظ';save.disabled=true}catch{save.textContent='تعذر الحفظ على الجهاز'}});report.addEventListener('click',()=>page('report'));actions.append(report,save);out.append(actions);}
function stats(){$('#total').textContent=history.length;$('#flagged').textContent=history.filter(x=>['high','medium'].includes(x.risk)).length;}
function renderHistory(){const out=$('#historyList');out.replaceChildren();if(!history.length){out.append(el('p','لا توجد نتائج محفوظة بعد.'));return;}for(const row of history){const div=el('div',undefined,'history-row'),text=el('div');text.append(el('strong',row.summary),el('small',new Date(row.time).toLocaleString('ar-SA')+' · '+(row.engine==='gemini'?'Gemini':'قواعد أولية')));div.append(text,el('span',riskNames[row.risk]||'غير حاسمة','badge risk-'+row.risk));out.append(div);}}
$('#clearHistory').addEventListener('click',()=>{history=[];localStorage.removeItem('fatin-history');stats();renderHistory()});
function makeReport(d){$('#reportText').value=['درع فطن — مسودة تقرير مؤشرات','التاريخ: '+new Date().toLocaleString('ar-SA'),'النتيجة: '+riskNames[d.risk],d.summary,'',...(d.indicators||[]).map(x=>x.title+'\nالدليل: '+x.evidence+'\nالتوضيح: '+x.explanation),'',d.file?'بصمة SHA-256: '+d.file.sha256:'','حدود الفحص: '+d.limitation,'','لم يُرسل هذا التقرير إلى أي جهة. يُراجع ويُستكمل قبل تقديمه.'].filter(Boolean).join('\n\n');}
$('#copyReport').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('#reportText').value);$('#reportStatus').textContent='تم النسخ.'}catch{$('#reportText').select();$('#reportStatus').textContent='حدد النص وانسخه يدويًا.'}});
$('#downloadReport').addEventListener('click',()=>{const b=new Blob(['\ufeff'+$('#reportText').value],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(b),a=el('a');a.href=url;a.download='fatin-report.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
function bubble(text,role){const b=el('div',text,'bubble '+role);$('#messages').append(b);$('#messages').scrollTop=$('#messages').scrollHeight;return b;}
$$('[data-question]').forEach(n=>n.addEventListener('click',()=>{$('#question').value=n.dataset.question;$('#question').focus()}));
$('#chatForm').addEventListener('submit',async e=>{e.preventDefault();if(!$('#chatConsent').checked)return;const msg=$('#question').value.trim();if(!msg)return;$('#chatError').textContent='';$('#chatBtn').disabled=true;bubble(msg,'user');$('#question').value='';const pending=bubble('جارٍ التفكير…','assistant');try{const d=await api('chat',{message:msg,ai_consent:true,context:last?JSON.stringify(last):''});pending.textContent=d.response;}catch(e){pending.textContent='تعذر الرد الآن.';$('#chatError').textContent=e.message;}finally{$('#chatBtn').disabled=false}});
$('#server').value=base;$('#token').value=token;
$('#saveSettings').addEventListener('click',async()=>{let v=$('#server').value.trim().replace(/\/$/,'');try{if(v){const u=new URL(v);if(u.protocol!=='https:'&&!(['localhost','127.0.0.1'].includes(u.hostname)&&u.protocol==='http:'))throw Error('استخدم HTTPS، أو HTTP للتشغيل المحلي فقط.');if(u.username||u.password||u.search||u.hash)throw Error('أدخل عنوان الخادم دون بيانات دخول أو معاملات.');}base=v;token=$('#token').value.trim();localStorage.setItem('fatin-server',base);sessionStorage.setItem('fatin-token',token);$('#settingsStatus').textContent=(await health())?'تم حفظ الإعدادات والاتصال بالخادم.':'حُفظت الإعدادات؛ تعذر الاتصال بالخادم.';}catch(e){$('#settingsStatus').textContent=e.message;}});
function protectionState(enabled){protectionEnabled=enabled;$('#protection').textContent=enabled?'إيقاف الحماية':'⬡ تفعيل الحماية';$('#protectionStatus').textContent=enabled?'الحماية مفعّلة في إضافة المتصفح.':'الحماية غير مفعّلة.';}
window.addEventListener('message',e=>{if(e.source!==window||e.origin!==location.origin||e.data?.source!=='fatin-extension')return;if(e.data.type==='status'){extensionReady=true;protectionState(!!e.data.enabled)}if(e.data.type==='error'){$('#protectionStatus').textContent=e.data.message||'تعذر تفعيل الحماية؛ افتح نافذة الإضافة.';}});
$('#protection').addEventListener('click',()=>{if(!extensionReady){$('#installDialog').showModal();return;}const enabled=!protectionEnabled;if(enabled&&!confirm('ستفحص الإضافة عناوين المواقع العامة، وترسلها دون معاملات الرابط إلى خادم فطن وGemini عند تفعيله. هل توافق؟'))return;window.postMessage({source:'fatin-web',type:'set-protection',enabled},location.origin);});
$('#closeDialog').addEventListener('click',()=>$('#installDialog').close());
window.postMessage({source:'fatin-web',type:'get-status'},location.origin);stats();health();
